//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace engsoft3
{
    using System;
    using System.Collections.Generic;
    
    public partial class img_fundo_tab
    {
        public int ID { get; set; }
        public string nome_fundo { get; set; }
        public byte[] conteudo_arquivo { get; set; }
        public string nome_arquivo { get; set; }
    }
}
