//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace engsoft3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ranking
    {
        public int ID { get; set; }
        public int ranking1 { get; set; }
        public int player { get; set; }
        public int partidas_jogadas { get; set; }
    
        public virtual player player1 { get; set; }
    }
}
